import { Ticket, Comment, User, Project } from '../types';

const STORAGE_KEYS = {
  TICKETS: 'bug-tracker-tickets',
  COMMENTS: 'bug-tracker-comments',
  USERS: 'bug-tracker-users',
  PROJECTS: 'bug-tracker-projects',
  CURRENT_USER: 'bug-tracker-current-user',
  CURRENT_PROJECT: 'bug-tracker-current-project',
  THEME: 'bug-tracker-theme',
};

// Initialize default data
const defaultUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@company.com',
    role: 'admin',
    name: 'System Administrator',
  },
  {
    id: '2',
    username: 'tester1',
    email: 'tester1@company.com',
    role: 'tester',
    name: 'John Tester',
  },
  {
    id: '3',
    username: 'tester2',
    email: 'tester2@company.com',
    role: 'tester',
    name: 'Jane Developer',
  },
];

const defaultProjects: Project[] = [
  {
    id: '1',
    name: 'FactuPro',
    description: 'Main e-commerce application',
    modules: ['Authentication', 'Product Catalog', 'Shopping Cart', 'Payment', 'User Profile', 'Admin Panel', 'Merchants', 'RRHH', 'Usuarios', 'Contactos', 'Productos'],
    createdAt: new Date().toISOString(),
    createdBy: '1',
  },
  {
    id: '2',
    name: 'Mobile App',
    description: 'iOS and Android mobile application',
    modules: ['Login', 'Dashboard', 'Notifications', 'Settings', 'Camera', 'Sync'],
    createdAt: new Date().toISOString(),
    createdBy: '1',
  },
];

const defaultTickets: Ticket[] = [
  {
    id: 'dt-merchants-1',
    projectId: '1',
    title: 'No se renderizan datos del merchant en primera carga',
    module: 'Merchants',
    description: 'No se renderizan en el frontend los datos del merchant en la primera carga, sí al hacer F5.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-2',
    projectId: '1',
    title: 'Creación de merchants sin nombre',
    module: 'Merchants',
    description: 'Se pueden crear merchants sin nombre. (Preguntar a Adri).',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-3',
    projectId: '1',
    title: 'Creación de merchants con NIF incorrecto',
    module: 'Merchants',
    description: 'Se pueden crear merchants con NIF incorrecto. (Preguntar a Adri).',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-4',
    projectId: '1',
    title: 'Impuestos con valores negativos o >100%',
    module: 'Merchants',
    description: 'Se pueden configurar impuestos en valores negativos y también mayores al 100%. Validar: no menor a 0; >100% está OK.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-5',
    projectId: '1',
    title: 'Falta poder eliminar merchant',
    module: 'Merchants',
    description: 'Falta poder eliminar merchant. (Se hace al final).',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-6',
    projectId: '1',
    title: 'Impuestos con notación científica',
    module: 'Merchants',
    description: 'Permite la creación de impuestos con valores como % 1e0 (notación científica).',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-7',
    projectId: '1',
    title: 'No se puede eliminar impuestos',
    module: 'Merchants',
    description: 'No se puede eliminar impuestos.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-merchants-8',
    projectId: '1',
    title: 'No se puede crear nuevas empresas',
    module: 'Merchants',
    description: 'No se puede crear nuevas empresas. (Ref: 6/6).',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  // --- Tickets Usuarios --- 
  {
    id: 'dt-usuarios-1',
    projectId: '1',
    title: 'Error al eliminar usuario y querer invitar a otro, no se despliega dropdown de roles.',
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-usuarios-2',
    projectId: '1',
    title: 'No se puede volver a invitar usuario con link vencido.',
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-usuarios-3',
    projectId: '1',
    title: 'No se puede volver a invitar usuario eliminado.',
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-usuarios-4',
    projectId: '1',
    title: 'Al cambiar rol de usuario activo, no se ve dropdown de opciones sin F5.',
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-usuarios-5',
    projectId: '1',
    title: "(Mejora) Agregar mensaje 'Email requerido' al agregar usuario sin email.",
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-usuarios-6',
    projectId: '1',
    title: '(Mejora) Agregar opción de reenviar link de invitación.',
    module: 'Usuarios',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  // --- Tickets Contactos --- 
  {
    id: 'dt-contactos-1',
    projectId: '1',
    title: "Botón 'Crear Contacto' en centro de pantalla no tiene acción.",
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-2',
    projectId: '1',
    title: 'Scroll no funciona al seleccionar impuesto en preferencias de nuevo contacto.',
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-3',
    projectId: '1',
    title: "Campo 'Este contacto es' no carga valor previo al editar.",
    module: 'Contactos',
    description: 'Originalmente marcado como bug corregido, registrar para seguimiento.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-4',
    projectId: '1',
    title: 'Vat ID no se valida correctamente.',
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket. ¿No lleva validación?',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-5',
    projectId: '1',
    title: "(Mejora) Quitar * de requerido en 'Descuento' y 'Días de vencimiento'.",
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-6',
    projectId: '1',
    title: "(Mejora) Setear moneda 'Euro' por defecto.",
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-7',
    projectId: '1',
    title: '(Mejora) Alertar si correo de contacto ya está en uso y pedir confirmación.',
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-8',
    projectId: '1',
    title: '(Mejora) Cambiar icono de sección de contactos.',
    module: 'Contactos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-contactos-9',
    projectId: '1',
    title: 'Problema con filtrado por etiquetas, toma etiquetas de productos.',
    module: 'Contactos',
    description: 'El sistema de filtrado por etiquetas en la sección de Contactos parece estar utilizando o mostrando etiquetas destinadas a Productos, causando confusión y resultados incorrectos.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  // --- Tickets Productos --- 
  {
    id: 'dt-productos-1',
    projectId: '1',
    title: "Al editar producto, solo se permite editar nombre, resto da 'Error inesperado'.",
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-2',
    projectId: '1',
    title: 'Empleado (no admin) puede crear productos aunque sale alert de prohibido.',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-3',
    projectId: '1',
    title: '(Mejora) Estructurar como en Holded, falta flechita desplegable (Inventario).',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-4',
    projectId: '1',
    title: '(Mejora) Poner Productos primero, y dentro Inventario y Servicios.',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-5',
    projectId: '1',
    title: '(Mejora) Cambiar icono de barra lateral para productos.',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-6',
    projectId: '1',
    title: "(Mejora) Agregar mensaje 'Nombre es un campo requerido' al agregar producto sin nombre.",
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-7',
    projectId: '1',
    title: "(Mejora) Cambiar mensaje 'Solo se permiten números positivos' por 'El precio debe ser mayor a 0' para precio negativo.",
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-8',
    projectId: '1',
    title: '(Mejora) Opción de importar productos en formatos clásicos.',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-productos-9',
    projectId: '1',
    title: '(Mejora) Agregar imágenes, stock, costo, SKU, etc. (V2).',
    module: 'Productos',
    description: 'Detalles pendientes para este ticket.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  // --- Tickets RRHH (Nueva Tanda) ---
  {
    id: 'dt-rrhh-1',
    projectId: '1',
    title: 'Al crear un nuevo contrato el botón “Cancelar” no cierra la ventana emergente.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-2',
    projectId: '1',
    title: 'Al editar un empleado y no efectuar cambios o hacerlo parcialmente el botón de Aceptar da un “Error de validación”',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-3',
    projectId: '1',
    title: 'No se puede invitar usuarios desde la sección RRHH ni eliminarlos, tampoco editar el Rol.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-4',
    projectId: '1',
    title: 'Al intentar Activar un contrato no se puede, da error y se queda abierto el modal sin poder cerrarlo.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-5',
    projectId: '1',
    title: 'Revisar variables para “Compromisos” en RRHH.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-6',
    projectId: '1',
    title: 'Root: botones Editar/Borrar registro empleado no funcionan (renderizar condicionalmente).',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-7',
    projectId: '1',
    title: 'Tracking Decisión: No se puede editar un contrato (definido por Bruno/Adri).',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-8',
    projectId: '1',
    title: 'Campo comentario al registrar jornada se rompe con texto largo.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-9',
    projectId: '1',
    title: 'Tiempo real de jornada no actualiza visualmente sin F5.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-10',
    projectId: '1',
    title: 'Texto “Actions” en lugar de “Acciones” en Control Horario.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-11',
    projectId: '1',
    title: 'Error RRHHC018 al registrar jornada sin contrato activo (mejorar mensaje).',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-12',
    projectId: '1',
    title: 'No se puede “Activar” contratos en RRHH.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'high',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-13',
    projectId: '1',
    title: 'Rol autorizado no puede CRUD ausencias; Admin tampoco.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-14',
    projectId: '1',
    title: '(Mejora) Admin: Ver detalles de contratos (ej. días de trabajo).',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-15',
    projectId: '1',
    title: 'Ausencias: validar solicitud solo días laborales / contabilizar correctamente.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-16',
    projectId: '1',
    title: 'Usuario trabajador puede ver ausencias de otros.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-17',
    projectId: '1',
    title: 'Empleado puede modificar jornadas aprobadas (bloquear o requerir reaprobación).',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-18',
    projectId: '1',
    title: 'No se puede crear contrato para fines de semana.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-19',
    projectId: '1',
    title: 'Considerar redondear horas de empleados a 2 decimales.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-20',
    projectId: '1',
    title: '(Mejora) Editar fecha nacimiento empleado: permitir escribir/saltar año.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-21',
    projectId: '1',
    title: '(Mejora) Alerta al crear contrato si empleado ya tiene uno activo.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-22',
    projectId: '1',
    title: '(Mejora) Filtrado por fechas para registros horarios.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-23',
    projectId: '1',
    title: '(Mejora) Enviar email a admin al crear ausencia.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-24',
    projectId: '1',
    title: '(Mejora) Ordenar lista de ausencias (recientes primero) o permitir elegir orden.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-25',
    projectId: '1',
    title: '(Mejora) Agregar columna “fecha de solicitud” en lista de ausencias.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'low',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  },
  {
    id: 'dt-rrhh-26',
    projectId: '1',
    title: '(Mejora) Alerta antes de eliminar jornada activa.',
    module: 'RRHH',
    description: 'Detalles pendientes para este ticket de RRHH.',
    notes: '',
    priority: 'medium',
    status: 'open',
    assignedTo: '1',
    createdBy: '1',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    attachments: [],
  }
];

export const initializeStorage = () => {
  if (!localStorage.getItem(STORAGE_KEYS.USERS)) {
    localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(defaultUsers));
  }
  if (!localStorage.getItem(STORAGE_KEYS.PROJECTS)) {
    localStorage.setItem(STORAGE_KEYS.PROJECTS, JSON.stringify(defaultProjects));
  }
  if (!localStorage.getItem(STORAGE_KEYS.TICKETS)) {
    localStorage.setItem(STORAGE_KEYS.TICKETS, JSON.stringify(defaultTickets));
  }
  if (!localStorage.getItem(STORAGE_KEYS.COMMENTS)) {
    localStorage.setItem(STORAGE_KEYS.COMMENTS, JSON.stringify([]));
  }
  if (!localStorage.getItem(STORAGE_KEYS.CURRENT_PROJECT)) {
    localStorage.setItem(STORAGE_KEYS.CURRENT_PROJECT, '1');
  }
  if (!localStorage.getItem(STORAGE_KEYS.THEME)) {
    localStorage.setItem(STORAGE_KEYS.THEME, 'light');
  }
};

export const getTickets = (): Ticket[] => {
  const tickets = localStorage.getItem(STORAGE_KEYS.TICKETS);
  return tickets ? JSON.parse(tickets) : [];
};

export const saveTickets = (tickets: Ticket[]) => {
  localStorage.setItem(STORAGE_KEYS.TICKETS, JSON.stringify(tickets));
};

export const getComments = (): Comment[] => {
  const comments = localStorage.getItem(STORAGE_KEYS.COMMENTS);
  return comments ? JSON.parse(comments) : [];
};

export const saveComments = (comments: Comment[]) => {
  localStorage.setItem(STORAGE_KEYS.COMMENTS, JSON.stringify(comments));
};

export const getUsers = (): User[] => {
  const users = localStorage.getItem(STORAGE_KEYS.USERS);
  return users ? JSON.parse(users) : defaultUsers;
};

export const saveUsers = (users: User[]) => {
  localStorage.setItem(STORAGE_KEYS.USERS, JSON.stringify(users));
};

export const getProjects = (): Project[] => {
  const projects = localStorage.getItem(STORAGE_KEYS.PROJECTS);
  return projects ? JSON.parse(projects) : defaultProjects;
};

export const saveProjects = (projects: Project[]) => {
  localStorage.setItem(STORAGE_KEYS.PROJECTS, JSON.stringify(projects));
};

export const getCurrentUser = (): User | null => {
  const user = localStorage.getItem(STORAGE_KEYS.CURRENT_USER);
  return user ? JSON.parse(user) : null;
};

export const setCurrentUser = (user: User | null) => {
  if (user) {
    localStorage.setItem(STORAGE_KEYS.CURRENT_USER, JSON.stringify(user));
  } else {
    localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);
  }
};

export const getCurrentProject = (): string => {
  return localStorage.getItem(STORAGE_KEYS.CURRENT_PROJECT) || '1';
};

export const setCurrentProject = (projectId: string) => {
  localStorage.setItem(STORAGE_KEYS.CURRENT_PROJECT, projectId);
};

export const getTheme = (): 'light' | 'dark' => {
  return (localStorage.getItem(STORAGE_KEYS.THEME) as 'light' | 'dark') || 'light';
};

export const setTheme = (theme: 'light' | 'dark') => {
  localStorage.setItem(STORAGE_KEYS.THEME, theme);
};

export const generateId = (): string => {
  return Date.now().toString() + Math.random().toString(36).substr(2, 9);
};